//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_3_6_2024.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lab_3_6_2024Entities : DbContext
    {
        public Lab_3_6_2024Entities()
            : base("name=Lab_3_6_2024Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<UserProjectRelation> UserProjectRelations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
